/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package try1;

import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nikhil
 */
public class login extends javax.swing.JFrame 
{
    Connection conn=conntry.connectdb();
    PreparedStatement ps=null;
    ResultSet rs=null;
    
    public login() {
        initComponents();
        conntry.connectdb();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        proffesion = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        Login_bt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bt_sign_in = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("LOG IN ");

        jLabel2.setText("Username");

        proffesion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Principal", "Student", "Teacher", "HOD", "Office staff", "Librarian Staff" }));

        jLabel3.setText("Password");

        Login_bt.setText("Log in");
        Login_bt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login_btMouseClicked(evt);
            }
        });
        Login_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_btActionPerformed(evt);
            }
        });

        jLabel4.setText("Not a member ? ");

        bt_sign_in.setBackground(new java.awt.Color(102, 0, 204));
        bt_sign_in.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bt_sign_in.setText("SIGN IN");
        bt_sign_in.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_sign_inMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(proffesion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(username)
                                    .addComponent(password)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(233, 233, 233)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_sign_in))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(311, 311, 311)
                            .addComponent(Login_bt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(359, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(proffesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Login_bt)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bt_sign_in))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_btActionPerformed
       
        
        
        
    }//GEN-LAST:event_Login_btActionPerformed

    private void bt_sign_inMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_sign_inMouseClicked
            new_sign_in a= new new_sign_in();
            this.setVisible(false);
            a.setVisible(true);
    }//GEN-LAST:event_bt_sign_inMouseClicked
	public int loginTask(String username,String password,String profession) {
		if(username.equals("") || username.length()>29 || profession.equals("") || password.equals("") || password.length()>15 )
         {
        	  return 0;
          }
    	 return 1; 
	}
    private void Login_btMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_btMouseClicked
        
    	String uname="nikhil";//username.getText();
    	String pswd="khartode";//password.getText();
    	String prf=proffesion.getSelectedItem().toString();
    	if(loginTask(uname,pswd,prf)==1) {
    		 JOptionPane.showMessageDialog(null, "login succesfull");
    		 if(proffesion.getSelectedItem().toString().equalsIgnoreCase("Teacher"))
             {
                 teacher_frame a=new teacher_frame();
                 this.setVisible(false);
                 a.setVisible(true);
             }
               if(proffesion.getSelectedItem().toString().equalsIgnoreCase("Student"))
             {
                 sign_in a=new sign_in();
                 this.setVisible(false);
                 a.setVisible(true);
             }
                 if(proffesion.getSelectedItem().toString().equalsIgnoreCase("Hod"))
             {
                 hod_frame a=new hod_frame();
                 this.setVisible(false);
                 a.setVisible(true);
             }  
                  if(proffesion.getSelectedItem().toString().equalsIgnoreCase("Office Staff"))
             {
                 office_staff_frame a=new office_staff_frame();
                 this.setVisible(false);
                 a.setVisible(true);
             }
                  if(proffesion.getSelectedItem().toString().equalsIgnoreCase("librarian Staff"))
             {
                 library_frame a=new library_frame();
                 this.setVisible(false);
                 a.setVisible(true);
             }
                   if(proffesion.getSelectedItem().toString().equalsIgnoreCase("Principal"))
             {
                 principal_frame a=new principal_frame();
                 this.setVisible(false);
                 a.setVisible(true);
             }
           
    	}
    	else {
    		JOptionPane.showMessageDialog(null, "login unsuccesfull");
    	}
    	
//        String login="Select * from login where username=? AND password=? AND post=?";
//        try{
//            ps=conn.prepareStatement(login);
//            ps.setString(1,username.getText());
//            ps.setString(2,password.getText());
//            ps.setString(3,proffesion.getSelectedItem().toString());
//            rs=ps.executeQuery();
//            if(rs.next())
//            {
//                 if(proffesion.getSelectedItem().toString().equalsIgnoreCase("Teacher"))
//                {
//                    teacher_frame a=new teacher_frame();
//                    this.setVisible(false);
//                    a.setVisible(true);
//                }
//                  if(proffesion.getSelectedItem().toString().equalsIgnoreCase("Student"))
//                {
//                    sign_in a=new sign_in();
//                    this.setVisible(false);
//                    a.setVisible(true);
//                }
//                    if(proffesion.getSelectedItem().toString().equalsIgnoreCase("Hod"))
//                {
//                    hod_frame a=new hod_frame();
//                    this.setVisible(false);
//                    a.setVisible(true);
//                }  
//                     if(proffesion.getSelectedItem().toString().equalsIgnoreCase("Office Staff"))
//                {
//                    office_staff_frame a=new office_staff_frame();
//                    this.setVisible(false);
//                    a.setVisible(true);
//                }
//                     if(proffesion.getSelectedItem().toString().equalsIgnoreCase("librarian Staff"))
//                {
//                    library_frame a=new library_frame();
//                    this.setVisible(false);
//                    a.setVisible(true);
//                }
//                      if(proffesion.getSelectedItem().toString().equalsIgnoreCase("Principal"))
//                {
//                    principal_frame a=new principal_frame();
//                    this.setVisible(false);
//                    a.setVisible(true);
//                }
//                JOptionPane.showMessageDialog(null,"Login successfull..");
//            }                
//             else
//                JOptionPane.showMessageDialog(null,"Login failed..");
//            
//        }catch(SQLException ex)
//        {
//            JOptionPane.showMessageDialog(null,ex);
//        }
//        
    }//GEN-LAST:event_Login_btMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException
    {
       conntry a=new conntry();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login_bt;
    private javax.swing.JLabel bt_sign_in;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox proffesion;
    private static javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
